# Generated by Django 5.2.7 on 2025-11-05 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule_type', models.CharField(choices=[('fixed_discount', 'Fixed Discount'), ('percent_discount', 'Percentage Discount')], max_length=20)),
                ('condition_value', models.DecimalField(decimal_places=2, help_text='Minimum cart total or quantity to apply the rule', max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, help_text='Amount or percentage to discount', max_digits=10)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
